In [2]:
import torch
# Mistake: Attempting to index a 2D tensor with three indices.
points = torch.tensor([[1, 2],
                       [3, 4]])
print("Original 2D Tensor:\n", points)

try:
    print("\nAttempting to index with three dimensions:")
    # This will raise an IndexError because 'points' is only 2D.
    print(points[0, 0, 0])  # Incorrect indexing
except IndexError as e:
    print("IndexError caught:", e)


Original 2D Tensor:
 tensor([[1, 2],
        [3, 4]])

Attempting to index with three dimensions:
IndexError caught: too many indices for tensor of dimension 2


In [4]:
# Mistake: Expecting that a subtensor is an independent copy.
# Here, slicing returns a view into the original tensor.
row_ref = points[0]      # This is just a view, not a copy
row_ref[0] = 999         # This modifies 'points' as well
print("\nAfter modifying 'row_ref' (a view):")
print("Original tensor:\n", points)
print("Subtensor 'row_ref':\n", row_ref)



After modifying 'row_ref' (a view):
Original tensor:
 tensor([[999.,   2.],
        [  3.,   4.]])
Subtensor 'row_ref':
 tensor([999.,   2.])


In [ ]:
# Explanation: The stride of a tensor tells you how many elements in the underlying storage 
# you need to skip to move by one unit along a particular dimension.
#
# For example, in a 2D tensor with shape (rows, columns), if the stride is (s0, s1):
#   - s0: the number of elements to skip to go to the next row.
#   - s1: the number of elements to skip to go to the next column.
#
# In our case:
print("\nTensor 'points':\n", points)
print("Shape of 'points':", points.shape)
print("Stride of 'points':", points.stride())
# For our 2x2 tensor, a common stride is (2, 1), meaning:
#   - To move from row 0 to row 1, skip 2 elements in the storage.
#   - To move from one column to the next in the same row, skip 1 element.


In [6]:
# Mistake: Expecting that transposing a tensor rearranges its underlying memory.
# Transposing returns a view with different stride values.
points_t = points.t()  # Transpose the tensor (swap rows and columns)
print("\nTransposed view 'points_t':\n", points_t)
print("Is 'points_t' contiguous?", points_t.is_contiguous())
print("Stride of original 'points':", points.stride())
print("Stride of transposed 'points_t':", points_t.stride())

# Note: 'points_t' is not contiguous. Its stride reflects the transposition.
# When a tensor is non-contiguous, operations like .view() may fail.

try:
    # This attempt to flatten may fail because 'points_t' is non-contiguous.
    flattened = points_t.view(-1)
    print("\nFlattened tensor:", flattened)
except RuntimeError as e:
    print("RuntimeError caught when trying to view a non-contiguous tensor:", e)



Transposed view 'points_t':
 tensor([[999.,   3.],
        [  2.,   4.]])
Is 'points_t' contiguous? False
Stride of original 'points': (2, 1)
Stride of transposed 'points_t': (1, 2)
RuntimeError caught when trying to view a non-contiguous tensor: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [ ]:
# Mistake: Modifying a transposed view and not realizing it affects the original tensor.
points_t[0, 1] = 1234
print("\nAfter modifying 'points_t':")
print("Transposed tensor 'points_t':\n", points_t)
print("Original tensor 'points' also changed:\n", points)


In [ ]:
# To avoid unwanted behavior when slicing, clone your tensor if you need an independent copy.
points = torch.tensor([[1.0, 2.0],
                       [3.0, 4.0]])
row_clone = points[0].clone()  # Now row_clone is independent.
row_clone[0] = 777
print("\nAfter cloning and modifying 'row_clone':")
print("Original tensor 'points':\n", points)
print("Cloned row 'row_clone':\n", row_clone)